// Generated by gencpp from file srv_tutorial/srv1.msg
// DO NOT EDIT!


#ifndef SRV_TUTORIAL_MESSAGE_SRV1_H
#define SRV_TUTORIAL_MESSAGE_SRV1_H

#include <ros/service_traits.h>


#include <srv_tutorial/srv1Request.h>
#include <srv_tutorial/srv1Response.h>


namespace srv_tutorial
{

struct srv1
{

typedef srv1Request Request;
typedef srv1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv1
} // namespace srv_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_tutorial::srv1 > {
  static const char* value()
  {
    return "f8e36621b04a3359422e55a9b256fdc3";
  }

  static const char* value(const ::srv_tutorial::srv1&) { return value(); }
};

template<>
struct DataType< ::srv_tutorial::srv1 > {
  static const char* value()
  {
    return "srv_tutorial/srv1";
  }

  static const char* value(const ::srv_tutorial::srv1&) { return value(); }
};


// service_traits::MD5Sum< ::srv_tutorial::srv1Request> should match
// service_traits::MD5Sum< ::srv_tutorial::srv1 >
template<>
struct MD5Sum< ::srv_tutorial::srv1Request>
{
  static const char* value()
  {
    return MD5Sum< ::srv_tutorial::srv1 >::value();
  }
  static const char* value(const ::srv_tutorial::srv1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_tutorial::srv1Request> should match
// service_traits::DataType< ::srv_tutorial::srv1 >
template<>
struct DataType< ::srv_tutorial::srv1Request>
{
  static const char* value()
  {
    return DataType< ::srv_tutorial::srv1 >::value();
  }
  static const char* value(const ::srv_tutorial::srv1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_tutorial::srv1Response> should match
// service_traits::MD5Sum< ::srv_tutorial::srv1 >
template<>
struct MD5Sum< ::srv_tutorial::srv1Response>
{
  static const char* value()
  {
    return MD5Sum< ::srv_tutorial::srv1 >::value();
  }
  static const char* value(const ::srv_tutorial::srv1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_tutorial::srv1Response> should match
// service_traits::DataType< ::srv_tutorial::srv1 >
template<>
struct DataType< ::srv_tutorial::srv1Response>
{
  static const char* value()
  {
    return DataType< ::srv_tutorial::srv1 >::value();
  }
  static const char* value(const ::srv_tutorial::srv1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_TUTORIAL_MESSAGE_SRV1_H
