// Generated by gencpp from file srv_tutorial/srv1Request.msg
// DO NOT EDIT!


#ifndef SRV_TUTORIAL_MESSAGE_SRV1REQUEST_H
#define SRV_TUTORIAL_MESSAGE_SRV1REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv_tutorial
{
template <class ContainerAllocator>
struct srv1Request_
{
  typedef srv1Request_<ContainerAllocator> Type;

  srv1Request_()
    : A(0)
    , B(0)
    , C(0)  {
    }
  srv1Request_(const ContainerAllocator& _alloc)
    : A(0)
    , B(0)
    , C(0)  {
  (void)_alloc;
    }



   typedef int8_t _A_type;
  _A_type A;

   typedef int8_t _B_type;
  _B_type B;

   typedef int8_t _C_type;
  _C_type C;





  typedef boost::shared_ptr< ::srv_tutorial::srv1Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv_tutorial::srv1Request_<ContainerAllocator> const> ConstPtr;

}; // struct srv1Request_

typedef ::srv_tutorial::srv1Request_<std::allocator<void> > srv1Request;

typedef boost::shared_ptr< ::srv_tutorial::srv1Request > srv1RequestPtr;
typedef boost::shared_ptr< ::srv_tutorial::srv1Request const> srv1RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv_tutorial::srv1Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv_tutorial::srv1Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srv_tutorial::srv1Request_<ContainerAllocator1> & lhs, const ::srv_tutorial::srv1Request_<ContainerAllocator2> & rhs)
{
  return lhs.A == rhs.A &&
    lhs.B == rhs.B &&
    lhs.C == rhs.C;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srv_tutorial::srv1Request_<ContainerAllocator1> & lhs, const ::srv_tutorial::srv1Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srv_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::srv_tutorial::srv1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_tutorial::srv1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_tutorial::srv1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_tutorial::srv1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_tutorial::srv1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_tutorial::srv1Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv_tutorial::srv1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f95c98c1d3f4b4904df88005f12f20e0";
  }

  static const char* value(const ::srv_tutorial::srv1Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf95c98c1d3f4b490ULL;
  static const uint64_t static_value2 = 0x4df88005f12f20e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::srv_tutorial::srv1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv_tutorial/srv1Request";
  }

  static const char* value(const ::srv_tutorial::srv1Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv_tutorial::srv1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 A\n"
"int8 B\n"
"int8 C\n"
;
  }

  static const char* value(const ::srv_tutorial::srv1Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv_tutorial::srv1Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
      stream.next(m.B);
      stream.next(m.C);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv1Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv_tutorial::srv1Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv_tutorial::srv1Request_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<int8_t>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<int8_t>::stream(s, indent + "  ", v.B);
    s << indent << "C: ";
    Printer<int8_t>::stream(s, indent + "  ", v.C);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_TUTORIAL_MESSAGE_SRV1REQUEST_H
