// Generated by gencpp from file vacuum_pkg/status_srvResponse.msg
// DO NOT EDIT!


#ifndef VACUUM_PKG_MESSAGE_STATUS_SRVRESPONSE_H
#define VACUUM_PKG_MESSAGE_STATUS_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vacuum_pkg/status_msg.h>

namespace vacuum_pkg
{
template <class ContainerAllocator>
struct status_srvResponse_
{
  typedef status_srvResponse_<ContainerAllocator> Type;

  status_srvResponse_()
    : header()
    , status()  {
    }
  status_srvResponse_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::vacuum_pkg::status_msg_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct status_srvResponse_

typedef ::vacuum_pkg::status_srvResponse_<std::allocator<void> > status_srvResponse;

typedef boost::shared_ptr< ::vacuum_pkg::status_srvResponse > status_srvResponsePtr;
typedef boost::shared_ptr< ::vacuum_pkg::status_srvResponse const> status_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vacuum_pkg::status_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vacuum_pkg::status_srvResponse_<ContainerAllocator1> & lhs, const ::vacuum_pkg::status_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vacuum_pkg::status_srvResponse_<ContainerAllocator1> & lhs, const ::vacuum_pkg::status_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vacuum_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0646b5edbc1a7a1956a8ea474e52ba1f";
  }

  static const char* value(const ::vacuum_pkg::status_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0646b5edbc1a7a19ULL;
  static const uint64_t static_value2 = 0x56a8ea474e52ba1fULL;
};

template<class ContainerAllocator>
struct DataType< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vacuum_pkg/status_srvResponse";
  }

  static const char* value(const ::vacuum_pkg::status_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"status_msg status # include the msg status defined in the package\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vacuum_pkg/status_msg\n"
"string ROOM_ID\n"
"string ROOM_NAME\n"
"float32 BATTERY\n"
;
  }

  static const char* value(const ::vacuum_pkg::status_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct status_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vacuum_pkg::status_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vacuum_pkg::status_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::vacuum_pkg::status_msg_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VACUUM_PKG_MESSAGE_STATUS_SRVRESPONSE_H
