// Generated by gencpp from file vacuum_pkg/status_srv.msg
// DO NOT EDIT!


#ifndef VACUUM_PKG_MESSAGE_STATUS_SRV_H
#define VACUUM_PKG_MESSAGE_STATUS_SRV_H

#include <ros/service_traits.h>


#include <vacuum_pkg/status_srvRequest.h>
#include <vacuum_pkg/status_srvResponse.h>


namespace vacuum_pkg
{

struct status_srv
{

typedef status_srvRequest Request;
typedef status_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct status_srv
} // namespace vacuum_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vacuum_pkg::status_srv > {
  static const char* value()
  {
    return "3718bc835b72cc299bc62d56555ebaea";
  }

  static const char* value(const ::vacuum_pkg::status_srv&) { return value(); }
};

template<>
struct DataType< ::vacuum_pkg::status_srv > {
  static const char* value()
  {
    return "vacuum_pkg/status_srv";
  }

  static const char* value(const ::vacuum_pkg::status_srv&) { return value(); }
};


// service_traits::MD5Sum< ::vacuum_pkg::status_srvRequest> should match
// service_traits::MD5Sum< ::vacuum_pkg::status_srv >
template<>
struct MD5Sum< ::vacuum_pkg::status_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vacuum_pkg::status_srv >::value();
  }
  static const char* value(const ::vacuum_pkg::status_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vacuum_pkg::status_srvRequest> should match
// service_traits::DataType< ::vacuum_pkg::status_srv >
template<>
struct DataType< ::vacuum_pkg::status_srvRequest>
{
  static const char* value()
  {
    return DataType< ::vacuum_pkg::status_srv >::value();
  }
  static const char* value(const ::vacuum_pkg::status_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vacuum_pkg::status_srvResponse> should match
// service_traits::MD5Sum< ::vacuum_pkg::status_srv >
template<>
struct MD5Sum< ::vacuum_pkg::status_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vacuum_pkg::status_srv >::value();
  }
  static const char* value(const ::vacuum_pkg::status_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vacuum_pkg::status_srvResponse> should match
// service_traits::DataType< ::vacuum_pkg::status_srv >
template<>
struct DataType< ::vacuum_pkg::status_srvResponse>
{
  static const char* value()
  {
    return DataType< ::vacuum_pkg::status_srv >::value();
  }
  static const char* value(const ::vacuum_pkg::status_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VACUUM_PKG_MESSAGE_STATUS_SRV_H
