(cl:defpackage vacuum_pkg-msg
  (:use )
  (:export
   "<STATUSACTION>"
   "STATUSACTION"
   "<STATUSACTIONFEEDBACK>"
   "STATUSACTIONFEEDBACK"
   "<STATUSACTIONGOAL>"
   "STATUSACTIONGOAL"
   "<STATUSACTIONRESULT>"
   "STATUSACTIONRESULT"
   "<STATUSFEEDBACK>"
   "STATUSFEEDBACK"
   "<STATUSGOAL>"
   "STATUSGOAL"
   "<STATUSRESULT>"
   "STATUSRESULT"
   "<STATUS_MSG>"
   "STATUS_MSG"
  ))

